Statement 1
CREATE TABLE EMP( 
    EMPNO NUMBER(6), 
    ENAME VARCHAR2(20) NOT NULL, 
    JOB VARCHAR2(10) NOT NULL, 
    MGR NUMBER94, 
    DEPTNO NUMBER(3), 
    SAL NUMBER(7,2), 
    COMM NUMBER(7,2), 
    HIREDATE DATE, 
    CONSTRAINT PK_EMP PRIMARY KEY (EMPNO), 
    CONSTRAINT FK_DEPTNO FOREIGN KEY (DEPTNO) REFERENCES DEPT (DEPTNO) 
    )
ORA-00902: invalid datatype

More Details: https://docs.oracle.com/error-help/db/ora-00902
  
Statement 2
CREATE TABLE EMP( 
    EMPNO NUMBER(6), 
    ENAME VARCHAR2(20) NOT NULL, 
    JOB VARCHAR2(10) NOT NULL, 
    MGR NUMBER94, 
    DEPTNO NUMBER(3), 
    SAL NUMBER(7,2), 
    COMM NUMBER(7,2), 
    HIREDATE DATE, 
    CONSTRAINT PK_EMP PRIMARY KEY (EMPNO), 
    CONSTRAINT FK_DEPTNO FOREIGN KEY (DEPTNO) REFERENCES DEPT (DEPTNO) 
    )
ORA-00902: invalid datatype

More Details: https://docs.oracle.com/error-help/db/ora-00902
  
Statement 3
CREATE TABLE EMP( 
    EMPNO NUMBER(6), 
    ENAME VARCHAR2(20) NOT NULL, 
    JOB VARCHAR2(10) NOT NULL, 
    MGR NUMBER(4), 
    DEPTNO NUMBER(3), 
    SAL NUMBER(7,2) 
    )
Table created.
  
Statement 4
DESCRIBE EMP
TABLE EMP
Column	Null?	Type
EMPNO	-	NUMBER(6,0)
ENAME	NOT NULL	VARCHAR2(20)
JOB	NOT NULL	VARCHAR2(10)
MGR	-	NUMBER(4,0)
DEPTNO	-	NUMBER(3,0)
SAL	-	NUMBER(7,2)
Download CSV
6 rows selected.
  
Statement 5
ALTER TABLE EMP ADD (COMMISION NUMBER(10) NOT NULL)
Table altered.
Statement 6
  
DESCRIBE EMP
TABLE EMP
Column	Null?	Type
EMPNO	-	NUMBER(6,0)
ENAME	NOT NULL	VARCHAR2(20)
JOB	NOT NULL	VARCHAR2(10)
MGR	-	NUMBER(4,0)
DEPTNO	-	NUMBER(3,0)
SAL	-	NUMBER(7,2)
COMMISION	NOT NULL	NUMBER(10,0)
Download CSV
7 rows selected.
  
Statement 7
ALTER TABLE EMP MODIFY JOB VARCHAR(20)
Table altered.
  
Statement 8
DESCRIBE EMP
TABLE EMP
Column	Null?	Type
EMPNO	-	NUMBER(6,0)
ENAME	NOT NULL	VARCHAR2(20)
JOB	NOT NULL	VARCHAR2(20)
MGR	-	NUMBER(4,0)
DEPTNO	-	NUMBER(3,0)
SAL	-	NUMBER(7,2)
COMMISION	NOT NULL	NUMBER(10,0)
Download CSV
7 rows selected.
  
Statement 9
CREATE  TABLE DEPT( 
    DEPTNO NUMBER(2) PRIMARY KEY, 
    DNAME VARCHAR2(10), 
    LOC VARCHAR2(10), 
)
ORA-00904: : invalid identifier

More Details: https://docs.oracle.com/error-help/db/ora-00904
  
Statement 10
CREATE  TABLE DEPT( 
    DEPTNO NUMBER(2) PRIMARY KEY, 
    DNAME VARCHAR2(10), 
    LOC VARCHAR2(10) 
)
Table created.
  
Statement 11
DESCRIBE DEPT
TABLE DEPT
Column	Null?	Type
DEPTNO	NOT NULL	NUMBER(2,0)
DNAME	-	VARCHAR2(10)
LOC	-	VARCHAR2(10)
Download CSV
3 rows selected.
  
Statement 12
ALTER TABLE EMP ADD CONSTRAINT PK_EMP PRIMARY KEY(EMPNO)
Table altered.
  
Statement 13
ALTER TABLE EMP ADD CONSTRAINT FK_DEPTNO FOREIGN KEY(DEPTNO) REFERENCES DEPT(DEPTNO)
Table altered.
  
Statement 14
DESCRIBE EMP
TABLE EMP
Column	Null?	Type
EMPNO	NOT NULL	NUMBER(6,0)
ENAME	NOT NULL	VARCHAR2(20)
JOB	NOT NULL	VARCHAR2(20)
MGR	-	NUMBER(4,0)
DEPTNO	-	NUMBER(3,0)
SAL	-	NUMBER(7,2)
COMMISION	NOT NULL	NUMBER(10,0)
Download CSV
7 rows selected.
  
Statement 15
ALTER TABLE EMP MODIFY SAL NUMBER(7,2) DEFAULT 5000
Table altered.
  
Statement 16
DESCRIBE EMP
TABLE EMP
Column	Null?	Type
EMPNO	NOT NULL	NUMBER(6,0)
ENAME	NOT NULL	VARCHAR2(20)
JOB	NOT NULL	VARCHAR2(20)
MGR	-	NUMBER(4,0)
DEPTNO	-	NUMBER(3,0)
SAL	-	NUMBER(7,2)
COMMISION	NOT NULL	NUMBER(10,0)
Download CSV
7 rows selected.
  
Statement 17
SELECT * FROM EMP
no data found
  
Statement 18
ALTER TABLE EMP ADD DOB DATE
Table altered.
  
Statement 19
DESCRIBE EMP
TABLE EMP
Column	Null?	Type
EMPNO	NOT NULL	NUMBER(6,0)
ENAME	NOT NULL	VARCHAR2(20)
JOB	NOT NULL	VARCHAR2(20)
MGR	-	NUMBER(4,0)
DEPTNO	-	NUMBER(3,0)
SAL	-	NUMBER(7,2)
COMMISION	NOT NULL	NUMBER(10,0)
DOB	-	DATE
Download CSV
8 rows selected.
  
Statement 20
ALTER TABLE EMP ADD DOJ DATE
Table altered.
  
Statement 21
DESCRIBE EMP
TABLE EMP
Column	Null?	Type
EMPNO	NOT NULL	NUMBER(6,0)
ENAME	NOT NULL	VARCHAR2(20)
JOB	NOT NULL	VARCHAR2(20)
MGR	-	NUMBER(4,0)
DEPTNO	-	NUMBER(3,0)
SAL	-	NUMBER(7,2)
COMMISION	NOT NULL	NUMBER(10,0)
DOB	-	DATE
DOJ	-	DATE
Download CSV
9 rows selected.
  
Statement 22
ALTER TABLE EMP DROP COLUMN DOJ
Table altered.
  
Statement 23
DESCRIBE EMP
TABLE EMP
Column	Null?	Type
EMPNO	NOT NULL	NUMBER(6,0)
ENAME	NOT NULL	VARCHAR2(20)
JOB	NOT NULL	VARCHAR2(20)
MGR	-	NUMBER(4,0)
DEPTNO	-	NUMBER(3,0)
SAL	-	NUMBER(7,2)
COMMISION	NOT NULL	NUMBER(10,0)
DOB	-	DATE
Download CSV
8 rows selected.
